# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/tuna/setup-makefiles.sh

# Pick up overlay for features that depend on non-open-source files

$(call inherit-product, vendor/samsung/tuna/tuna-vendor-blobs.mk)

PRODUCT_PACKAGES += \
    libfrsdk \
    libinvensense_mpl \
    libsec-ril.maguro \
    gps.omap4.maguro \
    lib_gs4dt.toro-common \
    gps.omap4.toro-common \
    libsec-ril_lte.toro \
    libims.toro \
    libims_jni.toro \
    libsec-ril_lte.toroplus

PRODUCT_PACKAGES += \
    libdrmwvmplugin \
    libwvdrmengine \
    libwvdrm_L3 \
    libwvm \
    libWVStreamControlAPI_L3
